CREATE TABLE TB_EQUIPAMENTO
(
    ID         BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    PATRIMONIO VARCHAR2(250) UNIQUE,
    TIPO       VARCHAR2(250) NOT NULL,
    MARCA      VARCHAR2(250) NOT NULL,
    IS_ATIVO   BOOLEAN       NOT NULL
)
