CREATE TABLE TB_PROBLEMA
(
    ID             BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO      VARCHAR2(4000) NOT NULL,
    ID_EQUIPAMENTO BIGINT(20)     NOT NULL,
    IS_ATIVO       BOOLEAN        NOT NULL,
    CONSTRAINT TB_PROBLEMA_TB_EQUIPAMENTO_ID_FK
        FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES TB_EQUIPAMENTO ON DELETE CASCADE
);

