CREATE TABLE TB_FUNCIONARIO
(
    ID        BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME      VARCHAR2(250) NOT NULL,
    MATRICULA VARCHAR2(100) NOT NULL UNIQUE,
    ID_TIPO   BIGINT(20)    NOT NULL,
    IS_ATIVO  BOOLEAN       NOT NULL,
    CONSTRAINT TB_FUNCIONARIO_TB_TIPO_FUNCIONARIO_ID_FK
        FOREIGN KEY (ID_TIPO) REFERENCES TB_TIPO_FUNCIONARIO
)
