CREATE TABLE TB_RESULTADO
(
    ID        BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DATA      DATE           NOT NULL,
    DESCRICAO VARCHAR2(4000) NOT NULL,
    ID_ORDEM_SERVICO BIGINT(20) NOT NULL,
    IS_ATIVO  BOOLEAN        NOT NULL,
    CONSTRAINT TB_RESULTADO_TB_ORDEM_SERVICO_ID_FK
        FOREIGN KEY (ID_ORDEM_SERVICO) REFERENCES TB_ORDEM_SERVICO ON DELETE CASCADE
)
